### ISSUE TITLE
Spaceses  and Char Limit development

### ISSUE THREAD

**Issue by harundogdu** [yusufalperendumlu/feedback-app#12]
![image](https://user-images.githubusercontent.com/43449361/231447871-82e31387-596d-4d57-b697-36948f76641a.png)

- Boşlular eşit olarak ayarlanmalı.
- En az ne kadar karakter girmemiz gerektiği, en fazla ne kadar karakter girmemiz gerektiği ve anlık olarak ne kadar karakter girdiğimiz gibi bilgileri içeren bir alan yapılabilir. Örnek: 10 ve altında girerse yada 255 ve üzerinde kırmızı renk olabilir. Ve bu feedback'i ekleyemez. Ortasında bir değerde ise yeşil renk olabilir.

**Comment by yusufalperendumlu** [comment]
- Verdiğiniz öneriler tamamlanmış olup projeye dahil edilmiştir. Teşekkür ederim :)
